void alarm1() {
  tone(buzzer, 100); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 1000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 2000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 5000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 500); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 5000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 2000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 50000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 140); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 1400); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 2400); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 4000); // Send 1KHz sound signal...
  delay(10);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 40); // Send 1KHz sound signal...
  delay(500);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  
}
void alarm3() {
  tone(buzzer, 100); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 1000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 2000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 5000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 500); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 5000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 2000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 50000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 140); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 1400); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 2400); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(100);
  tone(buzzer, 4000); // Send 1KHz sound signal...
  delay(100);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  delay(10);
  tone(buzzer, 40); // Send 1KHz sound signal...
  delay(500);        // ...for 1 sec
  noTone(buzzer);     // Stop sound...
  
}
void alarm2() {
  digitalWrite(buzzer, HIGH);
  delay(100);
  digitalWrite(buzzer, LOW);

}
